# Generated by Django 4.1.3 on 2022-11-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folk_rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=40)),
                ('banda', models.CharField(max_length=40)),
                ('publicacion', models.DateField()),
                ('tracks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funk_rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=40)),
                ('banda', models.CharField(max_length=40)),
                ('publicacion', models.DateField()),
                ('tracks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Indie_rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=40)),
                ('banda', models.CharField(max_length=40)),
                ('publicacion', models.DateField()),
                ('tracks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Posteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_post', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Psicodelic_rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=40)),
                ('banda', models.CharField(max_length=40)),
                ('publicacion', models.DateField()),
                ('tracks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rock_progresivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disco', models.CharField(max_length=40)),
                ('banda', models.CharField(max_length=40)),
                ('publicacion', models.DateField()),
                ('tracks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscriptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('acepta_mails', models.BooleanField()),
            ],
        ),
    ]
