# Generated by Django 4.1.3 on 2022-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolApp', '0002_we_delete_rock_progresivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicacion', models.DateField()),
                ('suscriptor', models.CharField(max_length=40)),
                ('critica', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Folk_rock',
        ),
        migrations.DeleteModel(
            name='Funk_rock',
        ),
        migrations.DeleteModel(
            name='Indie_rock',
        ),
        migrations.DeleteModel(
            name='Psicodelic_rock',
        ),
    ]
